# SPDX-License-Identifier: MIT
---
- name: Ensure Dovecot config is removed from Postfix.
  ansible.builtin.blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE ROLE DOVECOTSASL MANAGED BLOCK"
    state: absent
    validate: 'postconf %s'
  notify: restart postfix
